package serializer.peg;

public class PegOp {
    public final static String
    LT = "<",
    LE = "<=",
    GT = ">",
    GE = ">=",
    EQ = "==",
    NE = "!=",
    PLUS = "+",
    MINUS = "-",
    TIMES = "*",
    DIVIDE = "/",
    REMAINDER = "%",
    AND = "&&",
    OR = "||",
    BIN_AND = "&",
    BIN_OR = "|",
    XOR = "^",
    UMINUS = "---",
    UPLUS = "+++",
    NEG = "~",
    POSTINC = "_++",
    POSTDEC = "_--",
    PREINC = "++_",
    PREDEC = "--_",
    PLUS_EQ = "+=",
    MINUS_EQ = "-=",
    TIMES_EQ = "*=",
    DIVIDE_EQ = "/=",
    REM_EQ = "%=",
    ITE = "phi",
    LSHIFT = "<<",
    URSHIFT = ">>>",
    SRSHIFT = ">>",
    NOT = "!";
}
